url: https://ErasmusMC-Bioinformatics.github.io
baseurl:

# where things are
data_dir: metadata

# Build settings
markdown: kramdown
permalink: pretty



# General site settings
title: Choose Galaxy NL
email: a.stubbs@erasmusmc.nl
description: "Erasmus Medical Center Bioinformatcs Department"

welcome-message: Welcome to the Dutch Galaxy Portal!
welcome-subtitle: It's Nice To Meet You

banner-img: banner-dna.jpg


# Section headers
servers-header: Galaxy Servers
servers-tagline: Below is an overview of available public Galaxy instances in The Netherlands. Click on each logo to get more information
servers-footer:

projects-header: Projects
projects-tagline: Below you can find some Galaxy-related projects from around the country and the world.
projects-footer:

events-header: Events
events-tagline: List of Galaxy events, past and upcoming.
events-footer: If you would like to register your event here, please contact

partners-header: GalaxyNL partners
partners-tagline: The Dutch Galaxy Community
partners-footer: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.

about-header: About us
about-tagline:
about-footer:


#####################
#  COLLABORATIONS
#####################
collaborations:
- name: elixir
  logo: elixir.png

- name: dtl
  logo: dtl.jpg


####################
#  CONTACT
####################
contact-options:
- header: Visiting Address
  text:
    - line: Faculty Building
    - line: Room Ee15.79
    - line: Wytemaweg 80
    - line: 3015CN Rotterdam
    - line: The Netherlands
  links:
    - description: Route and Parking
      url: https://www.erasmusmc.nl/overerasmusmc/bereikbaarheid/erasmusmc_ziekenhuis/?lang=en

- header: Mailing Address
  text:
    - line: PO Box 2040
    - line: 3000 CA Rotterdam
    - line: The Netherlands

- header: E-mail us
  links:
    - description: bioinformatics@erasmusmc.nl
      url: mailto:bioinformatics@erasmusmc.nl
    - description: a.stubbs@erasmusmc.nl
      url: mailto:a.stubbs@erasmusmc.nl

- header: Call us
  text:
    - line: "Phone: +31 10 7043 491"
    - line: "Fax: +31 10 7044 161"


###############
#  FOOTER
###############
social:
  - title: github
    url: https://github.com/orgs/ErasmusMC-Bioinformatics
  - title: twitter
    url: https://twitter.com/ErasmusMC
